schema-version: v2
kind: plugin
metadata:
  name: infrastructure-test
  display-name: infrastructure-test
  description: teste-terraform
  version: 0.0.2
  picture: plugin.png
spec:
  type: infra
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  runtime:
    environment:
      - terraform-1-4
      - aws-cli-2
      - git-2
  repository: git@github.com:ronaldmirandazup/infra-stk.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Terraform
    - DevOps
  generates:
    connections:
      - type: aws-s3-conn
        alias: s3-infra-dev
        outputs:
          - from: infra_arn
            to: arn
          - from: bucket_name
            to: bucket_name
  stk-projects-only: false
  inputs:
  - label: Region
    type: text
    name: region
    help: Choose the name of the region.
    default: us-east-1
    required: true
  - label: Environment
    type: text
    name: environment
    help: Choose the name of the environment.
    default: development
    required: true
