schema-version: v2
kind: plugin
metadata:
  name: ronald-infrastructure
  display-name: ronald-infrastructure
  description: teste
  version: 0.0.1
  picture: plugin.png
spec:
  type: infra
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  runtime:
    environment:
      - terraform-1-4
      - aws-cli-2
      - git-2
  repository: git@github.com:ronaldmirandazup/infra-stk.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
  requires:
    connections:
      - type: aws-s3-conn
        alias: s3-bucket
  stk-projects-only: false
  inputs:
  - label: Type name of your resource
    name: resource
    type: text
    required: true 
    default: Client
    pattern: '([A-Z][a-z]+)+'
    help: 'Inform your resource name (e.g.: Client)'
  - label: Choose http method of new endpoint
    name: method
    type: text
    items:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    default: GET
    required: true
    help: 'Inform the method of the endpoint (e.g.: post or delete)'
  